### your site title here

title: Optimization course at Centrale Supélec
baseurl: /~durrc/Iut/optim # name of the repository

highlighter: rouge
markdown: kramdown
### exclude the instructions / write-up in the README.md

# Permalinks
# permalink:        pretty


#optimization
#compress.html
# compress_html:
#   clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
#   comments: ["<!-- ", " -->"]
#   endings: [all]
#   ignore:
#     envs: [local]
#   blanklines: false
#   profile: false
#   startings: []


# sass:
#  style: compressed

exclude:
- README.md


gems: [jekyll-seo-tag, jekyll-paginate]
